# command: bundle exec jekyll serve

title: TEST
# title: Lexxie's Minecraft JavaDocs
description: A small repository of Forge/Fabric JavaDocs for quick and easy use.
baseurl: ""
url: "https://lexxie.site"

# User settings
github_username: ladylexxie

# Google-Analytics
google-analytics:
  id: "G-K3TX5NPDG5"

# Clicky
clicky:
  id: "101400502"

exclude: ['.vscode', 'Gemfile', 'Gemfile.lock']
