remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Lexxie's Minecraft JavaDocs
description: A small repository of Forge/Fabric JavaDocs for quick and easy use.
show_downloads: true
google_analytics: G-K3TX5NPDG5
